### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by francismanalang** [francismanalang/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Make a data model to hold the x and y coordinates of the image
- [x] Use absolute positioning on the image
- [ ] Use the style property of element objects to change your car's top and left box offset styles
- [ ] Move your car every 16 milliseconds for a smooth movement.
